#!/bin/bash
#script that generates all the needed .html files from a template. 
#The only difference between the different pages is one "include" of 
#the content file, so we use sed to replace "CONTENT" in the template with 
#the actual subpage name

for SUBPAGE in index documentation downloads publications talks links contact; 
do
	echo $SUBPAGE
	sed "s/CONTENT/$SUBPAGE/" page_template > $SUBPAGE.html
done

#also generate publications and talks content...

/home/ndrost/bin/bibtex2html/bibtex2html -nokeys -nodoc -dl -d -r -o generated_publications publications/publications.bib
/home/ndrost/bin/bibtex2html/bibtex2html -nokeys -nodoc -dl -d -r -o generated_talks talks/talks.bib

